require: 
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
    - vendor/bundle/**/*
    - '**/db/schema.rb'
    - '**/db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'config.ru'
    - 'Rakefile'

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
  
Lint/UnusedMethodArgument:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# This exclusions are meant for RSpec 
Lint/ConstantDefinitionInBlock:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/VerifiedDoubleReference:
  EnforcedStyle: string

RSpec/NestedGroups:
  Max: 5